[project]
name = "nano-code"
version = "0.1.0"
description = "A simple coding agent CLI"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "click>=8.0.0",
    "rich>=13.0.0",
    "openai>=1.0.0",
    "python-dotenv>=1.0.0",
]

[project.scripts]
nano-code = "nano_code.cli:main"
